name: Weekly pharma RFP scrape

on:
  schedule:
    - cron:  '0 2 * * 1'      # 02:00 UTC every Monday
  workflow_dispatch:          # adds a manual “Run workflow” button

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - name: Run scraper
        run: python scrape.py

      # --- Option A: commit JSON back to repo (recommended) ---
      - name: Commit & push if changed
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name  "RFP-Bot"
          git config user.email "bot@users.noreply.github.com"
          git add latest_rfps.json data/*.pdf || true
          git diff --staged --quiet || \
             (git commit -m "Weekly update $(date -u '+%Y-%m-%d')" && \
              git push "https://${GH_TOKEN}@github.com/${{ github.repository }}.git" HEAD:main)

      # --- Option B: publish as build artifact (remove if using A) ---
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: latest_rfps
      #     path: latest_rfps.json
